### PR TITLE
341 add debian packaging to the release files

### PR DESCRIPTION
**Pull request by John15321**
Resolves https://github.com/sagiegurari/cargo-make/issues/341

Adds a `.deb. package to the release

### CODE REVIEW

**Comment by sagiegurari** [comment]
thanks a lot, will check it.

**Comment by sagiegurari** [comment]
@John15321 this looks cool, but can we update the deb file to include the platform on which it is supported?
i'm guessing i can't take that deb file and use it on arm, right?

**Comment by John15321** [comment]
> @John15321 this looks cool, but can we update the deb file to include the platform on which it is supported?
> i'm guessing i can't take that deb file and use it on arm, right?

The generated Deb file automatically has the version number of the package and it's architecture in the filename. At least it should

**Comment by John15321** [comment]
> @John15321 this looks cool, but can we update the deb file to include the platform on which it is supported?
> i'm guessing i can't take that deb file and use it on arm, right?



As you can see here it says it's `amd64`

**Comment by sagiegurari** [comment]
ah sorry for missing that. this is great. i'll take a closer look this week. sorry for the delay

**Comment by John15321** [comment]
> ah sorry for missing that. this is great. i'll take a closer look this week. sorry for the delay

No problem ☺️ I'm happy to help

**Comment by sagiegurari** [comment]
@John15321 i've been thinking about this one a lot.
1. why put these commands in the yaml and not in the makefile.toml? this way i can test it without github actions
2. if we are putting it in the toml, why not in the internal toml so others can use it as well. maybe in the rust.toml
3. if we are pushing it in, lets make it a flow with pre/post empty tasks so people can customize the flow
4. you said you thought about later doing it for fedora and such... so maybe we can even push it even further to have conditions based on dist and call the right task. such conditions are not supported by cargo-make (i can check env, os and such but not which linux you are running on) so you will have to build a condition using duckscript (or routing...)

so, something like this (not tested, just concept)

```toml
[tasks.package-native-flow]
dependencies = ["pre-package-native", "package-native", "post-package-native"]

[tasks.pre-package-native]
alias = "empty"

[tasks.post-package-native]
alias = "empty"

[tasks.package-native]
condition = { platforms = ["linux"] }
script = '''
#!@duckscript

# check which dist and call right task, for example lets say we found its a debian and we created a var named debian)
if ${debian}
  cm_run_task cargo-deb
end
'''

# since this is a cargo command, cargo-make will install cargo-deb if needed automatically.
[tasks.cargo-deb]
command = "cargo"
args = ["deb"]
```

the above is not tested and missing few pieces. 
wondering what you think?

**Comment by sagiegurari** [comment]
@John15321 this PR got closed since i deleted the branch.
can you rebuild the PR again please but also incorporate the suggestions in my previous message?

**Comment by John15321** [comment]
> @John15321 this PR got closed since i deleted the branch. can you rebuild the PR again please but also incorporate the suggestions in my previous message?

Im sorry I forget and didn't have time. I will do it this weekend

**Comment by sagiegurari** [comment]
no rush. i just don't want this to be lost by mistake

**Pull request closed without merging**
