### PR TITLE
Improve log readability, minor code cleanups

### PR DESCRIPTION
**Pull request by berkus**
- reduces log level of cargo metadata parsing step, this is not significantly important but noisy
- added an empty line before project tasks, makes it easier visually to find where a different project build started
- refactored up some code

### CODE REVIEW

**Comment by sagiegurari** [comment]
thanks for the PR. i see build is failing.

**Comment by berkus** [comment]
Example of the improvement:

image

**Comment by berkus** [comment]
> i see build is failing.

@sagiegurari will check

**Comment by sagiegurari** [comment]
@berkus looks good thanks. just fyi, it will probably be a while until i release this as its not big functional change or a bug fix.

**Pull request merged**
