### PR TITLE
Clippy installation fails on nightly

### LINKED ISSUE #290: Clippy installation fails nightly
**Describe the bug**
After I've updated my nightly toolchain to the latest update, my clippy had to be rebuild, so cargo-make tried to update it by failed.

**To Reproduce**
1. Update to latest nightly (or a toolchain that will trigger rebuild/reinstall of clippy)
2. Run `cargo-make install-clippy-any`

**Error Stack**
```console
[cargo-make] INFO - Execute Command: "cargo" "install" "--force" "--git" "https://github.com/rust-lang/rust-clippy/"
    Updating git repository `https://github.com/rust-lang/rust-clippy/`
error: multiple packages with binaries found: clippy, clippy_dev, clippy_dummy, clippy_workspace_tests
```

Changing the install arguments fixes the problem:
`install_crate_args = ["--git", "https://github.com/rust-lang/rust-clippy/", "clippy"]`

I wanted to fire the bug report and confirm this is the case, before making a PR.

Regards

### PR DESCRIPTION
**Pull request by elpiel**
Resolves #290

### CODE REVIEW

**Comment by sagiegurari** [comment]
Thanks will check it soon (got HW issues)

**Comment by elpiel** [comment]
I guess some lints are not present on the latest `clippy`?!
I am on holiday until Monday, so I will try to check it then.

**Comment by sagiegurari** [comment]
@elpiel is there an issue with the PR you need to check or can this be merged?
the build error is resolved and wasn't related to your PR

**Comment by elpiel** [comment]
No issues with my PR, thought that the build fail because of me.

**Comment by sagiegurari** [comment]
merged, thanks a lot!!!
will be published in the next version

**Pull request merged**
