### PR TITLE
0.17.0

### PR DESCRIPTION
**Pull request by sagiegurari**

### CODE REVIEW

**Comment by sagiegurari** [comment]
@ssokolow is there any feature missing and urgent? did you verify all changes?
i would like to release them but would prefer to add anything that is missing if needed first.

**Comment by ssokolow** [comment]
I'll block out some time within the next couple of days to complete and test the port of my justfile and let you know.

**Comment by sagiegurari** [comment]
@ssokolow thanks!!!

**Comment by ssokolow** [comment]
...and I just realized that I've been replying to this topic of conversation in issue #202. Sorry.

**Comment by sagiegurari** [comment]
@ssokolow I'm thinking of releasing this and any issue/change you need to bring in the next release.

**Comment by ssokolow** [comment]
That'd be reasonable. I don't remember any specific blockers and I've had to put my port on hold to work on other things anyway.

(If there's anything specific I still need to test out for you that I forgot about, I can make time for it, but the need for the features as a whole has been deferred until I get back to the project in question.)

**Pull request merged**
