### PR TITLE
Add sub-command alternative to the readme

### LINKED ISSUE #923: Sub-command docs improvement
### Feature Description
The current example for sub-commands using `extend` has some limitations, including the ability to list the allowed commands in the sub-command.

### Describe The Solution You'd Like
Use an external file for a sub command.

### Code Sample

```rust
[tasks.foo]
args = ["--makefile", "${FOO_CONFIG_DIR}/Makefile.foo.toml", "${@}"]
category = "Subcommands"
command = "makers"
description = "Foo subcommands"
```

Some benefits of this approach:
-  allows to use the usual options for `cargo-make` like `--list-all-steps` to get the sub-command specific commands
- commands don't require a specif prefix
- allows `[config]` options per sub-command

A limitation of this approach is the lack of auto-complete. I didn't investigate this yet.

### PR DESCRIPTION
**Pull request by janosimas**
fix #923

### CODE REVIEW

**Comment by sagiegurari** [comment]
@janosimas thanks for this and docs are great, but can you do a minor fix?
the readme.md is actually generated from both nav.md and content.md.
you need to update those files and not the readme file otherwise your content will be deleted.

**Comment by sagiegurari** [comment]
@janosimas just making sure you saw my comment

**Comment by janosimas** [comment]
Hi @sagiegurari , sorry, it has been some hectic days.
It is in my todo list.

**Comment by janosimas** [comment]
I rebased and updated nav.md and content.md

**Comment by sagiegurari** [comment]
@janosimas this is great, thanks a lot.
will merge and generate the readme later today

**Pull request merged**
