### PR TITLE
Fix typos in README.md

### PR DESCRIPTION
**Pull request by jayvdb**
More typos found by typos-cli, set up recently in https://github.com/sagiegurari/cargo-make/pull/1013

@ben1009, any idea why these didnt appear for you?

### CODE REVIEW

**Comment by sagiegurari** [comment]
@jayvdb thanks a lot, but that file is generated from content.md and nav.md so those need to change.

**Comment by jayvdb** [comment]
Ah that explains it.  https://github.com/sagiegurari/cargo-make/pull/1013 did change those, but the README wasnt regenerated

**Comment by sagiegurari** [comment]
i'll regenerate the file

**Comment by sagiegurari** [comment]
seems its already synced. so worth checking if those typos are also in content.md

**Comment by sagiegurari** [comment]
oh wait, forgot to pull. lol. fixed.

**Comment by sagiegurari** [comment]
closing this as it should be ok now... thanks for notifying me.

**Pull request closed without merging**
