### PR TITLE
version.rs: Use cargo search --limit=1

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by sagiegurari** [comment]
@jayvdb thanks a lot for the PR. i'll review it and merge.

**Comment by sagiegurari** [comment]
can we only keep the change relevant for the PR?
formatting I'll handle separately and its not related and may confuse others when looking at the commit.

**Comment by jayvdb** [comment]
moved the toml reformatting to https://github.com/sagiegurari/cargo-make/pull/575

I'll rebase this on top of master once that has been solved.

**Comment by sagiegurari** [comment]
can you please rebase your branch after i did the reformat.
that way i can see only the relevant changes.

**Comment by sagiegurari** [comment]
@jayvdb thanks a lot for the PR. merging to a new dev branch

**Pull request merged**
