### PR TITLE
Fix UNC prefix stripping inconsistency (Fixes #561)

### LINKED ISSUE #561: `CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY` is canonicalized with the `\\?\` prefix
### Describe The Bug
Unfortunately, something very annoying about Rust's `std::fs::canonicalize` is that on Windows, it prefixes `\\?\` to the path.

https://stackoverflow.com/a/21194605/7471684

Whilst this is all up to spec, and theoretically is correct, annoyingly A LOT of programs, commands, etc on Windows do not support this prefix. `robocopy`, `xcopy` are two culprits.

I'm sure there may be other environment variables that Cargo Make sets which have this problem.

There is a crate that works around this problem: https://docs.rs/dunce/1.0.1/dunce/

### To Reproduce
Use `CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY` on Windows

### PR DESCRIPTION
**Pull request by WilliamVenner**

### CODE REVIEW

**Comment by sagiegurari** [comment]
@WilliamVenner this is great, thanks a lot!
i'll check it out a bit more tomorrow and merge it. but from quick glance of the code, it looks good.

**Comment by sagiegurari** [comment]
@WilliamVenner code looks really great.
can you verify on windows that all these env vars look good and if not, maybe use your fix?
if needed, maybe create some util function so it can be easily reused?

CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE
CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY
CARGO_MAKE_WORKING_DIRECTORY
CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY
CARGO_MAKE_CRATE_TARGET_DIRECTORY
CARGO_MAKE_CRATE_CUSTOM_TRIPLE_TARGET_DIRECTORY
CARGO_MAKE_CARGO_HOME

**Comment by sagiegurari** [comment]
@WilliamVenner just making sure you saw my comment :)

**Comment by WilliamVenner** [comment]
Sorry! I have been really busy over the past week. Btw, edits are open to maintainers for my PR if there's anything you want to clean up before merge.

I did a quick test of those environment variables:

```batch
C:\Users\billy\$BLACKHOLE\adwdaw>echo C:\Users\billy\$BLACKHOLE\adwdaw\Makefile.toml
C:\Users\billy\$BLACKHOLE\adwdaw\Makefile.toml

C:\Users\billy\$BLACKHOLE\adwdaw>echo C:\Users\billy\$BLACKHOLE\adwdaw
C:\Users\billy\$BLACKHOLE\adwdaw

C:\Users\billy\$BLACKHOLE\adwdaw>echo C:\Users\billy\$BLACKHOLE\adwdaw
C:\Users\billy\$BLACKHOLE\adwdaw

C:\Users\billy\$BLACKHOLE\adwdaw>echo C:\Users\billy\$BLACKHOLE\adwdaw
C:\Users\billy\$BLACKHOLE\adwdaw

C:\Users\billy\$BLACKHOLE\adwdaw>echo C:\Users\billy\$BLACKHOLE\adwdaw\target
C:\Users\billy\$BLACKHOLE\adwdaw\target

C:\Users\billy\$BLACKHOLE\adwdaw>echo
ECHO is on.

C:\Users\billy\$BLACKHOLE\adwdaw>echo C:\Users\billy\.cargo
C:\Users\billy\.cargo
```

**Comment by sagiegurari** [comment]
thanks a lot. I'll be merging it soon.

**Comment by sagiegurari** [comment]
merging it to a new dev branch. thanks a lot for the PR!!!
i'll probably test few things more myself before publishing it.

**Pull request merged**
