### PR TITLE
Double Ctrl+C

### PR DESCRIPTION
**Pull request by MartinKavik**
Related issue: #374 

Resolves the problem when the `cargo-make` binary exits too early (because of receiving Ctrl+C signal) but the task command is still running (either it's shutting down or becoming a zombie process).

The first Ctrl+C press writes `Shutting down...` to the terminal and waits for the command to shut down gracefully. The second press kills the command and waits for its exit status.

Tested manually with a new "playground repo" [makers_tester](https://github.com/MartinKavik/makers_tester) and with [MoonZoon](https://github.com/MoonZoon/MoonZoon) examples. `cargo-make` unit tests pass (run in Git hooks). Tested on Windows.

I'm not sure if the `loop` is the most efficient implementation but I didn't want to introduce some async runtimes or complex streaming/channels in the code.

P.S. `cargo-make` writes `[cargo-make] INFO - Build Done in 22.51 seconds.` when the task is finished. The `Build Done` text doesn't make too much sense when the task is a running server or something like that. Just fyi.

### CODE REVIEW

**Comment by sagiegurari** [comment]
@MartinKavik first of all thanks a lot for the PR.
I got few concerns over the changes and its possibly just me, but I wonder maybe we should make this capability optional and turned on via config section in the makefile.toml.
By default, cargo-make will behave as today, but if turned on, we will get the new flow that you created.
This will allow us to avoid any blockers that might be introduced with such a change.
if your project requires it, you can set it in the makefile.toml and any contributor would have it turned on by default.
does it make sense? what do you think?

**Comment by MartinKavik** [comment]
> maybe we should make this capability optional and turned on via config section in the makefile.toml

No problem for me, I already have some basic configs in most makefiles, e.g.:
```toml
[config]
default_to_workspace = false
min_version = "0.32.15"

[config.modify_core_tasks]
private = true
namespace = "default"

[tasks.xxx]
```
so I can add another field when needed.

---

> By default, cargo-make will behave as today, but if turned on, we will get the new flow that you created.
This will allow us to avoid any blockers that might be introduced with such a change.

Perhaps we can draw inspiration from Rust and introduce something like:
```toml
[config]
unstable_features = ["ctrl_c_handling"]
```
Just an idea, I don't have a strong opinion about it.

---

Should I try to implement this gate/configuration and somehow resolve codecov problems or do you want to do it by yourself?

**Comment by sagiegurari** [comment]
> Should I try to implement this gate/configuration and somehow resolve codecov problems or do you want to do it by yourself?

your choice. I would love you to take it but i'm ok if you want me to push the PR as is and do the changes no top. just say what you prefer.

> unstable_features = ["ctrl_c_handling"]

interesting, on one hand, we can more things here easily, on the other hand, its less type safe.
I like it. lets go for it.

**Comment by MartinKavik** [comment]
Added a new commit `unstable_features`.

Updated `makers_tester`'s makefiles for manual testing: https://github.com/MartinKavik/makers_tester/commit/2ee95483f6e296531f04505be6886063dfe99067

Implementation notes: 
- I tried to make _unstable features_ as typed as possible. 
- The function `UnstableFeature::to_env_name` could be optimized a bit to return `&'static str` instead of `String` but we would need to integrate a crate like `strum` to automatically derive env names from the enum variants and then maybe another crate to join env name parts during the compilation.
- I've chosen the implementation with env vars to add a bit more flexibility for users and to not need to painfully pass the config values through too many functions. 
- I've neither updated docs nor written new unit tests for the functionality - I think the tasks would be more suitable for you, if possible.

**Comment by sagiegurari** [comment]
@MartinKavik amazing job. don't have any critical code comments, might do minor changes later but overall looks great.
I'll do so minor testing tomorrow and merge this.
the whole type safety you did for the unstable features is awesome. thanks a lot for that

**Comment by sagiegurari** [comment]
@MartinKavik going to merge this in. looks awesome.
will probably do few minor nit changes and also fix the build by defining a new min rust version for it.
many thanks for the help here

**Pull request merged**
